### ISSUE TITLE
Group files according to language 

### ISSUE THREAD

**Issue by Sahiljawale** [Sahiljawale/CodeChef#5]

**Comment by Ansh-Sarkar** [comment]
Hey @Sahiljawale ! Would like to work on this. Will be sorting the files into respective folders based on their language and then updating the ```README.md``` to contain a list of all the files under each folder in order to give a sort of snapshot into the contents of the repo.

Do assign this issue to me if you feel it would be a valuable addition to the project. Thanks !

**Comment by Sahiljawale** [comment]
@Ansh-Sarkar 
I will suggest doing this work in our free time, don't waste much of your time on this.

**Comment by Ansh-Sarkar** [comment]
Sure. Thank you :smile:
